version: '3.8'

services:
  production_db:
    image: postgres:13
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - "${DATABASE_VOLUME}:/var/lib/postgresql/data"

  test_db:
    image: postgres:13
    container_name: ${DATABASE_CONTAINER_NAME_TEST}
    environment:
      POSTGRES_USER: ${DATABASE_USER_TEST}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD_TEST}
      POSTGRES_DB: ${DATABASE_DB_TEST}
    ports:
      - "${DATABASE_PORT_TEST}:5432"
    volumes:
      - "${DATABASE_VOLUME_TEST}:/var/lib/postgresql/data"

volumes:
  gerenciador_vendas:
  gerenciador_vendas_test:
