"""adjuste date_birthday

Revision ID: 646b30d8bd9b
Revises: e137abf1b670
Create Date: 2024-06-07 21:44:30.838779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646b30d8bd9b'
down_revision: Union[str, None] = 'e137abf1b670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_birthday', sa.Date(), nullable=False))
    op.drop_column('users', 'data_birthday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('data_birthday', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('users', 'date_birthday')
    # ### end Alembic commands ###
